version: '3'

services:
  container_docker:
    build:
      context: .
    container_name: container_docker
    image: container_docker:$IMAGE_TAG
    volumes:
      - /usr/share/zoneinfo/America/Sao_Palo:/etc/localtime
    ports:
      - "3000:3000"
    networks:
      - default